version: "3.8"
services:
  wco-node:
    build:
      context: ../..
      dockerfile: wco-v2-framework/deployment/docker/Dockerfile
    container_name: wco-node
    ports:
      - "3000:3000"
    volumes:
      - ./data:/usr/src/app/data
    restart: unless-stopped
